# Generated by Django 3.0.2 on 2020-02-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.DecimalField(decimal_places=0, max_digits=100)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
    ]
